## Importing required libraries

In [1]:
#import pandas and numpy
import pandas as pd
import numpy as np

### Read Death Rates Dataset

In [3]:
death_rate_df = pd.read_excel("DeathRates.xlsx", index_col='State') #index_col eliminated the automatically
                                                                    #generated index and used state as index
death_rate_df.head()

,All cancer types combined,Brain and other nervous system,Breast,Cervix,Colorectum,Esophagus,Kidney and renal pelvis,Larynx,Leukemia,Liver and intrahepatic bile duct,...,Myeloma,Non-Hodgkin lymphoma,Oral cavity and pharynx,Ovary,Pancreas,Prostate,Stomach,Thyroid,Urinary bladder,Uterine corpus
State,,,,,,,,,,,,,,,,,,,,,
Alabama,10520,320,730,110,910,250,210,70,340,510,...,210,270,220,210,830,480,190,0,290,140
Alaska,1030,0,70,0,110,0,0,0,0,70,...,0,0,0,0,80,60,0,0,0,0
Arizona,13200,410,910,80,1210,340,350,70,540,710,...,270,410,200,310,1120,820,240,60,410,240
Arkansas,6460,190,390,60,560,140,190,50,210,310,...,120,190,110,120,450,430,100,0,130,110
California,60970,2070,4690,520,5470,1420,1280,250,2340,3680,...,1280,2150,1070,1390,5080,4130,1710,310,1620,1480

### Importing Dataset
### Incident rate dataset

In [11]:
incident_rate_df = pd.read_excel("IncRate.xlsx",sheet_name=1,header=6, index_col="State") #sheet names start at index 0,,header removes unnecessary head info
incident_rate_df.head()

,All cancer types combined / Both sexes combined,All cancer types combined / Female,All cancer types combined / Male,Brain and other nervous system / Both sexes combined,Brain and other nervous system / Female,Brain and other nervous system / Male,Breast / Both sexes combined,Breast / Female,Breast / Male,Cervix / Both sexes combined,...,Testis / Male,Thyroid / Both sexes combined,Thyroid / Female,Thyroid / Male,Urinary bladder / Both sexes combined,Urinary bladder / Female,Urinary bladder / Male,Uterine corpus / Both sexes combined,Uterine corpus / Female,Uterine corpus / Male
State,,,,,,,,,,,,,,,,,,,,,
All U.S. combined,449,423,487.9,6.5,5.5,7.6,126.9 - Female breast cancer only.,126.9,NaN,7.7,...,5.7,14.1,20.7,7.3,19.7,8.5,34,27.4,27,NaN
Alabama,450.8,404.1,515.2,6.3,5.5,7.3,121.4 - Female breast cancer only.,121.4,NaN,9.4,...,4.4,9.9,14.5,5.1,17.8,7.4,31.6,20.3,20.3,NaN
Alaska,418.6,403.8,440.7,6.6,5.9,7.2,121.9 - Female breast cancer only.,121.9,NaN,7.9,...,6,12.5,19.4,6.3,20.6,8.1,34.5,25.1,25.1,NaN
Arizona,385.7,368.5,410.3,5.9,5,6.9,114.2 - Female breast cancer only.,114.2,NaN,6.5,...,5.5,13.1,20.9,6.4,18.4,7.6,31.1,23.4,23.4,NaN
Arkansas,479,430.9,543.5,6.8,5.7,8.3,119.5 - Female breast cancer only.,119.5,NaN,9.5,...,5.2,12.6,18.4,6.6,19.9,8.1,34.9,25,25,NaN

In [12]:
incident_rate_df.shape

(53, 78)

### Importing New Cases Estimates dataset

In [14]:
new_case_estimate_df = pd.read_excel("NewCaseEstimates.xlsx",index_col="State")
new_case_estimate_df.head()

,All cancer types combined,Brain and other nervous system,Breast- Female breast cancer only.,Cervix,Colorectum,Esophagus,Hodgkin lymphoma,Kidney and renal pelvis,Larynx,Leukemia,...,Non-Hodgkin lymphoma,Oral cavity and pharynx,Ovary,Pancreas,Prostate,Stomach,Testis,Thyroid,Urinary bladder,Uterine corpus
State,,,,,,,,,,,,,,,,,,,,,
Alabama,30210,370,4280,240,2510,300,120,1290,250,780,...,1000,860,310,960,4650,390,110,450,1140,800
Alaska,3250,60,530,0,320,50,0,160,0,90,...,110,120,0,120,460,70,0,80,160,100
Arizona,39970,550,6110,290,3150,460,170,1900,200,1090,...,1680,1010,450,1340,4680,540,270,900,1910,1320
Arkansas,18610,220,2440,160,1530,180,80,790,150,520,...,690,540,180,570,2510,230,80,340,710,570
California,189220,2610,31720,1640,15880,1800,790,7630,810,5630,...,8500,5370,2250,6310,26890,3440,1240,4990,7620,7470

### ALL US INC RATE Dataset

In [18]:
all_us_df = pd.read_excel("IncRate.xlsx",sheet_name=0,header=6)
all_us_df

,Cancer Type,Both sexes combined,Female,Male
0,All cancer types combined,449,423.0,487.9
1,Brain and other nervous system,6.5,5.5,7.6
2,Breast,126.9 - Female breast cancer only.,126.9,NaN
3,Cervix,7.7,7.7,NaN
4,Colon (excluding rectum),25.4,23.0,28.1
5,Colorectum,36.5,31.6,42.1
6,Esophagus,4.5,1.8,7.8
7,Hodgkin lymphoma,2.6,2.3,3.0
8,Kidney and renal pelvis,17.1,11.8,23.2
9,Larynx,3.1,1.2,5.4
10,Leukemia,14.2,11.0,18.1
11,Liver and intrahepatic bile duct,8.6,4.7,13.1
12,Lung and bronchus,57.3,50.8,65.8
13,Melanoma of the skin,22.7,18.0,28.9
14,Myeloma,7,5.7,8.6
15,Non-Hodgkin lymphoma,19.2,15.9,23.1
16,Oral cavity and pharynx,11.9,6.5,18.1
17,Ovary,10.7,10.7,NaN
18,Pancreas,13.1,11.5,14.9
19,Prostate,106.4,NaN,106.4
20,Rectum,11.1,8.6,13.9
21,Stomach,6.5,4.6,8.7
22,Testis,5.7,NaN,5.7
23,Thyroid,14.1,20.7,7.3
24,Urinary bladder,19.7,8.5,34.0
25,Uterine corpus,27.4,27.0,NaN

In [19]:
## Replacing NaN values with 0
all_us_df.fillna(0,inplace=True)
all_us_df.head()

,Cancer Type,Both sexes combined,Female,Male
0,All cancer types combined,449,423.0,487.9
1,Brain and other nervous system,6.5,5.5,7.6
2,Breast,126.9 - Female breast cancer only.,126.9,0.0
3,Cervix,7.7,7.7,0.0
4,Colon (excluding rectum),25.4,23.0,28.1

In [21]:
# Query a specific column
all_us_df[['Both sexes combined']]

                   Both sexes combined
0                                  449
1                                  6.5
2   126.9 - Female breast cancer only.
3                                  7.7
4                                 25.4
5                                 36.5
6                                  4.5
7                                  2.6
8                                 17.1
9                                  3.1
10                                14.2
11                                 8.6
12                                57.3
13                                22.7
14                                   7
15                                19.2
16                                11.9
17                                10.7
18                                13.1
19                               106.4
20                                11.1
21                                 6.5
22                                 5.7
23                                14.1
24                                19.7
25                                27.4

In [26]:
# CONVERTING COLUMN VALUES TO NUMERIC
all_us_df[["Both sexes combined"]].apply(pd.to_numeric,errors='coerce',axis=1)
all_us_df.head()

,Cancer Type,Both sexes combined,Female,Male
0,All cancer types combined,449,423.0,487.9
1,Brain and other nervous system,6.5,5.5,7.6
2,Breast,126.9 - Female breast cancer only.,126.9,0.0
3,Cervix,7.7,7.7,0.0
4,Colon (excluding rectum),25.4,23.0,28.1

In [27]:
all_us_df.values

array([['All cancer types combined', '449', 423.0, 487.9],
       ['Brain and other nervous system', '6.5', 5.5, 7.6],
       ['Breast', '126.9 - Female breast cancer only.', 126.9, 0.0],
       ['Cervix', '7.7', 7.7, 0.0],
       ['Colon (excluding rectum)', '25.4', 23.0, 28.1],
       ['Colorectum', '36.5', 31.6, 42.1],
       ['Esophagus', '4.5', 1.8, 7.8],
       ['Hodgkin lymphoma', '2.6', 2.3, 3.0],
       ['Kidney and renal pelvis', '17.1', 11.8, 23.2],
       ['Larynx', '3.1', 1.2, 5.4],
       ['Leukemia', '14.2', 11.0, 18.1],
       ['Liver and intrahepatic bile duct', '8.6', 4.7, 13.1],
       ['Lung and bronchus', '57.3', 50.8, 65.8],
       ['Melanoma of the skin', '22.7', 18.0, 28.9],
       ['Myeloma', '7', 5.7, 8.6],
       ['Non-Hodgkin lymphoma', '19.2', 15.9, 23.1],
       ['Oral cavity and pharynx', '11.9', 6.5, 18.1],
       ['Ovary', '10.7', 10.7, 0.0],
       ['Pancreas', '13.1', 11.5, 14.9],
       ['Prostate', '106.4', 0.0, 106.4],
       ['Rectum', '11.1', 8.6, 13.9],
       ['Stomach', '6.5', 4.6, 8.7],
       ['Testis', '5.7', 0.0, 5.7],
       ['Thyroid', '14.1', 20.7, 7.3],
       ['Urinary bladder', '19.7', 8.5, 34.0],
       ['Uterine corpus', '27.4', 27.0, 0.0]], dtype=object)

In [33]:
all_us_df.replace(to_replace='126.9 - Female breast cancer only',value='nan', inplace=True)
all_us_df

                         Cancer Type Both sexes combined  Female   Male
0          All cancer types combined                 449   423.0  487.9
1     Brain and other nervous system                 6.5     5.5    7.6
2                             Breast                 nan   126.9    0.0
3                             Cervix                 7.7     7.7    0.0
4           Colon (excluding rectum)                25.4    23.0   28.1
5                         Colorectum                36.5    31.6   42.1
6                          Esophagus                 4.5     1.8    7.8
7                   Hodgkin lymphoma                 2.6     2.3    3.0
8            Kidney and renal pelvis                17.1    11.8   23.2
9                             Larynx                 3.1     1.2    5.4
10                          Leukemia                14.2    11.0   18.1
11  Liver and intrahepatic bile duct                 8.6     4.7   13.1
12                 Lung and bronchus                57.3    50.8   65.8
13              Melanoma of the skin                22.7    18.0   28.9
14                           Myeloma                   7     5.7    8.6
15              Non-Hodgkin lymphoma                19.2    15.9   23.1
16           Oral cavity and pharynx                11.9     6.5   18.1
17                             Ovary                10.7    10.7    0.0
18                          Pancreas                13.1    11.5   14.9
19                          Prostate               106.4     0.0  106.4
20                            Rectum                11.1     8.6   13.9
21                           Stomach                 6.5     4.6    8.7
22                            Testis                 5.7     0.0    5.7
23                           Thyroid                14.1    20.7    7.3
24                   Urinary bladder                19.7     8.5   34.0
25                    Uterine corpus                27.4    27.0    0.0

In [32]:
#DISPLAY ALL DATA TYPES
all_us_df.dtypes

Cancer Type             object
Both sexes combined     object
Female                 float64
Male                   float64
dtype: object

## Data Cleaning


### Checking for null values

In [39]:
# checking incident rate
incident_rate_df.isnull().sum()

All cancer types combined / Both sexes combined          0
All cancer types combined / Female                       0
All cancer types combined / Male                         0
Brain and other nervous system / Both sexes combined     0
Brain and other nervous system / Female                  0
                                                        ..
Urinary bladder / Female                                 0
Urinary bladder / Male                                   0
Uterine corpus / Both sexes combined                     0
Uterine corpus / Female                                  0
Uterine corpus / Male                                   53
Length: 78, dtype: int64